# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
    - label: Nieuws
      path: nieuws
      class: first
    - label: Verzekeringen
      path: verzekeringen
    - label: Beleggingen
      path: beleggingen 
    - label: Offerte
      path: offerte 
    - label: Partners
      path: partners 
    - label: Contact
      path: contact 
    - label: Documenten
      path: documenten 
    - label: facebook
      path: haha
      class: social 
    - label: linkedin
      path: linkedin
      class: social
